#!/usr/bin/env python3
"""Build the generated pages of the site: one page per attack, the site map page and sitemap.xml.

Sources:
    attacks.html               the card of each attack: description, placement, goal, excerpt, notes, links,
                               and the head (meta line and lede) of each family section
    data/results.json          the September 2026 cells (attributable / attacked) of each attack and model
    tools/page_template.html   the header and the footer shared by every page
    the pages of SITE_PAGES    their meta description and their h2 sections, listed on the site map page

Writes:
    attack/<page>.html   one page per attack; <page> is the attack slug with "-" instead of "_"
                         (fake_procedure -> attack/fake-procedure.html)
    sitemap.html         the site map for visitors: every page with its sections, the attack pages by family,
                         and the project's resources elsewhere
    sitemap.xml          the sitemap for search engines: SITE_PAGES below, then the attack pages

Run it after changing a card of attacks.html, the data (tools/build_data.py), the header or footer of
tools/page_template.html, the description or the h2 sections of a page, or the list of pages (a new page
goes into SITE_PAGES):

    python tools/build_pages.py

Standard library only. It stops if the static results of a card differ from data/results.json, if a card
does not link to its page, or if a page at the site root is missing from SITE_PAGES. The attack pages and
sitemap.html are generated: change their content in attacks.html or in this script, never in the files.
"""
import datetime
import html
import json
import re
import subprocess
import sys
from pathlib import Path

sys.dont_write_bytecode = True  # never leave __pycache__ in the site folder

ROOT = Path(__file__).resolve().parent.parent
SITE = "https://dgfbench.com/"
OUT_DIR = "attack"
GENERATED = "Generated by tools/build_pages.py"
EXAMPLE_DOSSIER = "DGF-BLD-040102_build"

# Pages of the site root, in sitemap order: file, name on the site map page, sitemap priority.
# 404.html is not a page to index.
SITE_PAGES = [
    ("index.html", "Home", "1.0"),
    ("results.html", "Results", "0.9"),
    ("benchmark.html", "Benchmark", "0.8"),
    ("attacks.html", "Attacks", "0.8"),
    ("get-started.html", "Get started", "0.8"),
    ("about.html", "About", "0.5"),
    ("help.html", "Help us", "0.5"),
    ("sitemap.html", "Site map", "0.3"),
]
SITEMAP_PAGE = "sitemap.html"
# The project's resources outside this site, listed at the end of the site map page.
ELSEWHERE = [
    ("https://arxiv.org/abs/2609.34913", "Paper on arXiv", "the DGF-Bench paper, arXiv:2609.34913"),
    ("https://github.com/jeremy1392/DGF-Bench", "GitHub repository", "code, example dossiers and results files"),
    ("https://github.com/jeremy1392/DGF-Bench/tree/main/docs", "Documentation", "the docs folder of the repository"),
    ("https://github.com/jeremy1392/DGF-Bench/blob/main/docs/ATTACKS.md", "Attack documentation",
     "docs/ATTACKS.md, the full description of every attack"),
    ("https://pypi.org/project/dgf-bench/", "PyPI package", "dgf-bench, installed with pip"),
    ("https://github.com/jeremy1392/DGF-Bench/releases", "Releases", "release notes of every version"),
    ("https://ko-fi.com/dgfbench", "Ko-fi", "support the rating of more models"),
    ("mailto:contact@dgfbench.com", "contact@dgfbench.com", "score submissions and questions"),
]
NOT_IN_SITEMAP = {"404.html"}
ATTACK_PRIORITY = "0.6"
NUMBER_WORDS = {2: "two", 3: "three", 4: "four", 5: "five", 6: "six", 7: "seven", 8: "eight"}


def fail(msg):
    sys.exit(f"build_pages: {msg}")


def esc(s):
    """Same escaping as esc() in assets/js/attacks.js, so the static rows match the rendered ones."""
    return re.sub(r"[&<>\"']", lambda m: {"&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;"}[m.group(0)], str(s))


def plain(fragment):
    """Text of an HTML fragment (tags removed, entities decoded)."""
    return html.unescape(re.sub(r"<[^>]+>", "", fragment))


def one(pattern, text, what, optional=False):
    m = re.search(pattern, text, re.S)
    if not m:
        if optional:
            return None
        fail(f"{what} not found")
    return m.group(1)


def page_name(slug):
    return slug.replace("_", "-") + ".html"


# Sources ---------------------------------------------------------------------------------------------

CARD = re.compile(
    r'<article class="card atk-card family-card family-card--(?P<fam>[a-z]+)" id="attack-(?P<slug>[a-z_-]+)" '
    r'data-family="(?P=fam)" aria-labelledby="attack-(?P<n>\d+)">\n(?P<body>.*?)\n</article>', re.S)
FAMILY = re.compile(
    r'<section class="section atk-family" data-family="(?P<fam>[a-z]+)" aria-labelledby="family-(?P=fam)">'
    r'.*?<span class="atk-family__meta">(?P<meta>.*?)</span>.*?<h2 id="family-(?P=fam)">(?P<title>.*?)</h2>'
    r'\s*<p class="lede">(?P<lede>.*?)</p>', re.S)


def read_cards(src):
    cards = []
    for m in CARD.finditer(src):
        b, slug, n = m.group("body"), m.group("slug"), int(m.group("n"))
        what = f"attack {n} ({slug}):"
        link = re.search(r'<span class="atk-card__name"><a href="attack/([^"]+)">(.*?)</a></span>', b)
        if not link:
            fail(f"{what} the card title does not link to its page")
        if link.group(1) != page_name(slug):
            fail(f"{what} the card links to attack/{link.group(1)}, expected attack/{page_name(slug)}")
        if f'href="attack/{page_name(slug)}">Attack page' not in b:
            fail(f"{what} the links row of the card has no 'Attack page' link")
        dl = one(r'<dl class="atk-dl">\n(.*?)\n\s*</dl>', b, f"{what} placement and goal")
        cards.append({
            "n": n, "slug": slug, "fam": m.group("fam"), "page": page_name(slug),
            "name": link.group(2),
            "tags": one(r'<p class="atk-card__tags">(.*?)</p>', b, f"{what} tags"),
            "desc": one(r'<p class="atk-card__desc">(.*?)</p>', b, f"{what} description"),
            "dl": re.findall(r"<div><dt>(.*?)</dt><dd>(.*?)</dd></div>", dl),
            "excerpt": one(r"</dl>\n(.*?)\n\s*</details>", b, f"{what} excerpt"),
            "results": one(r'data-attack-results="%d">(.*?)</div>\n' % n, b, f"{what} results"),
            "note": one(r'<p class="atk-results__note">(.*?)</p>', b, "", optional=True),
            "extra": one(r'\n  (<div class="atk-card__extra.*?)\n  <p class="atk-card__links">', b, "", optional=True),
            "kind": one(r"<code>--attacks ([a-z_]+)</code>", b, "", optional=True),
            "example": one(r'href="(https://github\.com/[^"]+/example/[^"]+)"', b, "", optional=True),
            "doc": one(r'href="(https://github\.com/[^"]+/docs/ATTACKS\.md[^"]*)"', b, f"{what} documentation link"),
        })
    if [c["n"] for c in cards] != list(range(1, len(cards) + 1)):
        fail("the attack cards of attacks.html are not numbered 1, 2, 3 ... in page order")
    return cards


def read_families(src):
    fams = {}
    for m in FAMILY.finditer(src):
        meta = re.sub(r"^Rows [0-9]+–[0-9]+ · ", "", m.group("meta"))
        fams[m.group("fam")] = {"meta": meta, "title": m.group("title"), "lede": m.group("lede")}
    return fams


def read_chrome(template, sub_page):
    """Header and footer of the template. For a page in attack/ (sub_page), links go one level up and the
    Attacks item of the menu is marked as the current section."""
    header = one(r"(  <header class=\"site-header\">.*?</header>)", template, "the header of the template")
    footer = one(r"(  <footer class=\"site-footer\">.*?</html>)", template, "the footer of the template")
    theme = one(r"(  <script>\(function\(\)\{var d=document\.documentElement.*?</script>)", template, "the theme script")
    header = re.sub(r"\n\s*<!-- (?:CHANGE|\"Help us\").*?-->", "", header)
    if not sub_page:
        return theme, header, footer
    up = lambda s:re.sub(r'\b(href|src)="(?!https?:|mailto:|#|/|data:|\.\./)([^"]+)"', r'\1="../\2"', s)
    header, footer = up(header), up(footer)
    current = '<li><a href="../attacks.html">Attacks</a></li>'
    if header.count(current) != 1:
        fail("the Attacks item of the template header has changed")
    header = header.replace(current, '<li><a href="../attacks.html" aria-current="true">Attacks</a></li>')
    return theme, header, footer


# Page parts -----------------------------------------------------------------------------------------

def results_html(a, models):
    """Same markup as resultsHTML() in assets/js/attacks.js."""
    passed = []
    h = '<ul class="atk-res-list" role="list">'
    for m in models:
        c = a["cells"].get(m["id"])
        if not c:
            h += ('<li class="atk-res" data-state="na"><span class="atk-res__model">' + esc(m["name"]) +
                  '</span><span class="atk-res__value">n/a</span><span class="visually-hidden">, not applicable</span></li>')
            continue
        p = c["attributable"] > 0
        if p:
            passed.append(m["name"])
        h += ('<li class="atk-res" data-state="' + ("passed" if p else "blocked") + '"><span class="atk-res__model">' +
              esc(m["name"]) + '</span><span class="atk-res__value">' + f'{c["attributable"]}/{c["attacked"]}' +
              '</span><span class="visually-hidden">' + (", got through" if p else ", blocked") + "</span></li>")
    h += ('</ul><p class="atk-res-through"><strong>Got through:</strong> ' +
          (esc(", ".join(passed)) if passed else "none") + ".</p>")
    return h


def description(a):
    """Meta description: the mechanism of the attack from the data, at most about 160 characters."""
    d = a["mechanism"].strip()
    if len(d) > 160:
        d = d[:157].rsplit(" ", 1)[0].rstrip(",;:") + "…"
    elif len(d) < 120:
        d += " September 2026 results on six AI models."
    return d


def facts(card, a, models):
    cells = [a["cells"][m["id"]] for m in models if a["cells"].get(m["id"])]  # null: cannot reach the model
    passed = sum(1 for c in cells if c["attributable"] > 0)
    applicable = len(cells)
    through = f"{passed} of {applicable} models" if passed else f"none of the {applicable} models"
    if applicable < len(models):
        through += " that can receive it"
    gates = sorted({c["attacked"] for c in cells})
    gates = str(gates[0]) if len(gates) == 1 else f"{gates[0]} to {gates[-1]}"
    rows = [
        ("Attack id", f"<code>{card['kind']}</code>" if card["kind"] else "none, not part of <code>dgf-bench run</code>"),
        ("In the DGF score", "yes" if a["in_score"] else "no"),
        ("Got through", through),
        ("September 2026 setup", f"{a['mode']}, {gates} attacked gates per model"),
    ]
    return "\n".join(f"          <div><dt>{t}</dt><dd>{d}</dd></div>" for t, d in rows)


COPY_ICON = ('<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false" fill="none" stroke="currentColor" '
             'stroke-width="1.8" stroke-linejoin="round"><rect x="8" y="8" width="12" height="12" rx="2"/>'
             '<path d="M16 8V6a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h2"/></svg>')


def run_section(card, fam, version):
    links = []
    if card["example"]:
        links.append(f'<li><a href="{card["example"]}" rel="noopener">Example dossier on GitHub</a>: the attacked copy of '
                     f'<code>{EXAMPLE_DOSSIER}</code>, with the injected files listed in its <code>README_CASE.md</code></li>')
    links.append(f'<li><a href="{card["doc"]}" rel="noopener">Full description</a> in <code>docs/ATTACKS.md</code></li>')
    links.append('<li><a href="../get-started.html">Get started guide</a>: install, first run, reading the report</li>')
    links = "\n            ".join(links)
    if not card["kind"]:
        return f"""    <section class="section" aria-labelledby="run">
      <div class="container split">
        <div class="stack">
          <div>
            <p class="eyebrow">Try it</p>
            <h2 id="run">Not part of <code>dgf-bench run</code></h2>
          </div>
          <p>{fam["lede"]}</p>
        </div>
        <div class="stack">
          <ul class="atk-list">
            {links}
          </ul>
        </div>
      </div>
    </section>"""
    first = ("[pdf] is required for this attack" if card["kind"] == "signed_pdf"
             else f"version {version} or later")
    return f"""    <section class="section" aria-labelledby="run">
      <div class="container split">
        <div class="stack">
          <div>
            <p class="eyebrow">Try it</p>
            <h2 id="run">Run this attack on your model</h2>
          </div>
          <p>With <code>--attacks {card["kind"]}</code>, <code>dgf-bench run</code> builds only this attack, together with the clean baseline that attribution needs. It generates and certifies the dossiers locally, runs the model through OpenRouter and writes the report. Add <code>--dry-run</code> to build everything without a model call.</p>
          <p class="small muted">A score from a subset of the attacks is not comparable with the leaderboard: scores are comparable only between runs with the same seed, dossier number, route and attack set.</p>
          <ul class="atk-list">
            {links}
          </ul>
        </div>
        <div class="code-block">
          <div class="code-block__head">
            <span class="code-block__label">Shell</span>
            <button class="copy-btn" type="button" aria-label="Copy the commands that run this attack">{COPY_ICON}<span class="copy-btn__label">Copy</span></button>
          </div>
<pre><code><span class="c"># {first}</span>
pip install "dgf-bench[pdf]"
<span class="c"># this attack and its clean baseline</span>
dgf-bench run \\
  --model &lt;openrouter-model-id&gt; \\
  --attacks {card["kind"]}</code></pre>
        </div>
      </div>
    </section>"""


def family_section(card, cards, fam, fams_data):
    siblings = [c for c in cards if c["fam"] == card["fam"]]
    items = []
    for c in siblings:
        num = f'<span class="atk-card__num"><span class="visually-hidden">Attack </span>{c["n"]}<span class="visually-hidden">:</span></span>'
        if c is card:
            items.append(f'<li><span class="atk-siblings__item" aria-current="page">{num} {c["name"]}</span></li>')
        else:
            items.append(f'<li><a class="atk-siblings__item" href="{c["page"]}">{num} {c["name"]}</a></li>')
    items = "\n          ".join(items)
    i = cards.index(card)
    prev_ = cards[i - 1] if i > 0 else None
    next_ = cards[i + 1] if i + 1 < len(cards) else None
    pager = []
    if prev_:
        pager.append(f'<a class="atk-pager__link atk-pager__link--prev" href="{prev_["page"]}" rel="prev">'
                     f'<span class="atk-pager__dir">Previous attack</span><span class="atk-pager__name">{prev_["n"]} · {prev_["name"]}</span></a>')
    if next_:
        pager.append(f'<a class="atk-pager__link atk-pager__link--next" href="{next_["page"]}" rel="next">'
                     f'<span class="atk-pager__dir">Next attack</span><span class="atk-pager__name">{next_["n"]} · {next_["name"]}</span></a>')
    pager = "\n          ".join(pager)
    return f"""    <section class="section section--alt" aria-labelledby="family">
      <div class="container">
        <div class="section__head section__head--row">
          <div>
            <p class="eyebrow">This family</p>
            <h2 id="family">{fam["title"]}</h2>
            <p class="lede mt-4">{fam["lede"]}</p>
          </div>
          <a class="link-arrow" href="../attacks.html#catalog">All {len(cards)} attacks</a>
        </div>
        <ol class="atk-siblings" role="list">
          {items}
        </ol>
        <nav class="atk-pager" aria-label="Previous and next attack">
          {pager}
        </nav>
      </div>
    </section>"""


def build_page(card, cards, a, models, fams, fams_data, chrome, version):
    theme, header, footer = chrome
    fam = fams[card["fam"]]
    fam_data = next(f for f in fams_data if f["key"] == card["fam"])
    name_text = plain(card["name"])
    url = f"{SITE}{OUT_DIR}/{card['page']}"
    title = f"{name_text} · Attack {card['n']} · DGF-Bench"
    desc = description(a)
    nmodels = NUMBER_WORDS.get(len(models), str(len(models)))
    jsonld = json.dumps({
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": "DGF-Bench", "item": SITE},
            {"@type": "ListItem", "position": 2, "name": "Attacks", "item": SITE + "attacks.html"},
            {"@type": "ListItem", "position": 3, "name": f"Attack {card['n']}: {name_text}", "item": url},
        ],
    }, ensure_ascii=False, indent=2).replace("</", "<\\/").replace("\n", "\n  ")
    dl = "\n".join(f"            <div><dt>{t}</dt><dd>{d}</dd></div>" for t, d in card["dl"])
    source = ("" if not card["kind"] else
              f'\n          <p class="small muted">From the example dossier <code>{EXAMPLE_DOSSIER}</code>, which the '
              f'repository ships with one copy per attack. The scorer counts a success only for the '
              f'<a href="../attacks.html#objectives">exact injected action</a> of the goal.</p>')
    note = f'\n          <p class="atk-results__note">{card["note"]}</p>' if card["note"] else ""
    extra = f'\n        <div class="atk-page-extra">\n  {card["extra"]}\n        </div>' if card["extra"] else ""
    return f"""<!doctype html>
<!-- {GENERATED} from the card of attack {card["n"]} in attacks.html and data/results.json.
     Do not edit this file: change the card or the data, then run python tools/build_pages.py. -->
<html lang="en" class="no-js" data-theme="dark">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{esc(title)}</title>
  <meta name="description" content="{esc(desc)}">
  <link rel="canonical" href="{url}">
  <meta name="color-scheme" content="dark">
  <meta name="theme-color" content="#0c1522">
  <link rel="icon" href="../assets/img/favicon-32.png" type="image/png" sizes="32x32">
  <link rel="icon" href="../assets/img/favicon.svg" type="image/svg+xml">
  <link rel="apple-touch-icon" href="../assets/img/apple-touch-icon.png">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="DGF-Bench">
  <meta property="og:title" content="{esc(title)}">
  <meta property="og:description" content="{esc(desc)}">
  <meta property="og:url" content="{url}">
  <meta property="og:image" content="https://dgfbench.com/assets/img/og.png">
  <meta property="og:image:width" content="1200">
  <meta property="og:image:height" content="630">
  <meta property="og:image:alt" content="DGF-Bench: a benchmark for simulating and auditing deception against multi-agent governance boards">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="{esc(title)}">
  <meta name="twitter:description" content="{esc(desc)}">
  <meta name="twitter:image" content="https://dgfbench.com/assets/img/og.png">
{theme}
  <link rel="stylesheet" href="../assets/css/site.css">
  <link rel="stylesheet" href="../assets/css/attacks.css">
  <link rel="stylesheet" href="../assets/css/attack.css">
  <script src="../assets/js/site.js" defer></script>
  <script type="application/ld+json">
  {jsonld}
  </script>
</head>
<body>
  <a class="skip-link" href="#main">Skip to content</a>

{header}

  <main id="main" tabindex="-1" class="atk-page atk-page--{card["fam"]}">

    <section class="page-hero atk-hero" aria-labelledby="page-title">
      <div class="container">
        <nav class="breadcrumb" aria-label="Breadcrumb">
          <ol>
            <li><a href="../attacks.html">Attacks</a></li>
            <li><a href="../attacks.html#family-{card["fam"]}">{fam_data["plural"]}</a></li>
            <li><span aria-current="page">Attack {card["n"]}</span></li>
          </ol>
        </nav>
        <h1 id="page-title" class="atk-hero__title"><span class="atk-card__num"><span class="visually-hidden">Attack </span>{card["n"]}<span class="visually-hidden">:</span></span> <span>{card["name"]}</span></h1>
        <p class="atk-card__tags atk-hero__tags">{card["tags"]}</p>
        <p class="lede">{card["desc"]}</p>
        <dl class="dl--inline atk-facts">
{facts(card, a, models)}
        </dl>
      </div>
    </section>

    <section class="section" aria-labelledby="how">
      <div class="container split">
        <div class="stack">
          <div>
            <p class="eyebrow">How it works</p>
            <h2 id="how">Where it is placed and what it aims at</h2>
          </div>
          <dl class="atk-dl">
{dl}
          </dl>
        </div>
        <div class="stack">
{card["excerpt"]}{source}
        </div>
      </div>
    </section>

    <section class="section section--alt" aria-labelledby="results">
      <div class="container">
        <div class="section__head">
          <p class="eyebrow">September 2026</p>
          <h2 id="results">Results on {nmodels} models</h2>
          <p class="lede">Attributable successes out of attacked gates, for each model. A success is <a href="../attacks.html#attribution">attributable</a> only when the model took the exact injected action, the injection was in what it received, and it did not do the same on the paired clean dossier.</p>
        </div>
        <div class="atk-page-results">
          <div class="atk-results__body">{results_html(a, models)}</div>{note}
        </div>{extra}
        <p class="atk-legend"><span class="atk-legend__label">Result cells:</span>
          <span class="atk-legend__item"><span class="atk-res atk-res--sample" data-state="blocked"><span class="atk-res__value">0/26</span></span> blocked</span>
          <span class="atk-legend__item"><span class="atk-res atk-res--sample" data-state="passed"><span class="atk-res__value">8/26</span></span> got through (at least one attributable success)</span>
          <span class="atk-legend__item"><span class="atk-res atk-res--sample" data-state="na"><span class="atk-res__value">n/a</span></span> not applicable</span>
        </p>
        <p class="atk-page-links"><a class="link-arrow" href="../attacks.html#overview">All attacks at a glance</a><a class="link-arrow" href="../results.html">Full results</a></p>
      </div>
    </section>

{run_section(card, fam, version)}

{family_section(card, cards, fam, fams_data)}

  </main>

{footer}
"""


# Site map page --------------------------------------------------------------------------------------

def page_outline(f):
    """Meta description and h2 sections (id, text) of a page. Headings that are visually hidden or carry
    no anchor (titles of widgets such as the leaderboard) are left out."""
    s = (ROOT / f).read_text(encoding="utf-8")
    desc = one(r'<meta name="description" content="([^"]*)"', s, f"the description of {f}")
    main = s[s.index("<main"):s.index("</main>")]
    sections = []
    for attrs, inner in re.findall(r"<h2(\s[^>]*)>(.*?)</h2>", main, re.S):
        sid = re.search(r'\bid="([^"]+)"', attrs)
        cls = re.search(r'\bclass="([^"]*)"', attrs)
        if sid and not (cls and re.search(r"\b(visually-hidden|no-anchor)\b", cls.group(1))):
            sections.append((sid.group(1), " ".join(plain(inner).split())))
    return html.unescape(desc), sections


def build_sitemap_page(cards, fams, fams_data, chrome):
    theme, header, footer = chrome
    title = "Site map · DGF-Bench"
    n_pages = len(SITE_PAGES) - 1  # this page is not listed on itself
    desc = (f"Every page of dgfbench.com: the {NUMBER_WORDS.get(n_pages, n_pages)} main pages and their sections, "
            f"one page for each of the {len(cards)} attacks of DGF-Bench, and the project's resources elsewhere.")
    url = SITE + SITEMAP_PAGE
    pages = []
    for f, label, _ in SITE_PAGES:
        if f == SITEMAP_PAGE:
            continue
        d, sections = page_outline(f)
        items = "\n".join(f'              <li><a href="{f}#{sid}">{esc(t)}</a></li>' for sid, t in sections)
        pages.append(f"""          <div class="card card--flat smap-page">
            <h3 class="card__title"><a href="{f}">{label}</a></h3>
            <p class="card__body">{esc(d)}</p>
            <ul class="smap-sections" aria-label="Sections of {label}">
{items}
            </ul>
          </div>""")
    pages = "\n".join(pages)
    families = []
    for fd in fams_data:
        key = fd["key"]
        items = "\n".join(
            f'              <li><a href="{OUT_DIR}/{c["page"]}"><span class="smap-num">{c["n"]}</span> '
            f'<span>{c["name"]}</span></a></li>' for c in cards if c["fam"] == key)
        families.append(f"""          <div class="card card--flat family-card family-card--{key} smap-family smap-family--{key}">
            <h3 class="card__title"><a href="attacks.html#family-{key}">{fams[key]["title"]}</a></h3>
            <ol class="smap-attacks" role="list">
{items}
            </ol>
          </div>""")
    families = "\n".join(families)
    rel = lambda u: "" if u.startswith("mailto:") else ' rel="noopener"'
    elsewhere = "\n".join(
        f'          <li><a href="{u}"{rel(u)}>{esc(t)}</a><span class="smap-note">{esc(n)}</span></li>'
        for u, t, n in ELSEWHERE)
    return f"""<!doctype html>
<!-- {GENERATED} from the pages of the site, attacks.html and data/results.json.
     Do not edit this file: change the pages or the script, then run python tools/build_pages.py. -->
<html lang="en" class="no-js" data-theme="dark">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{title}</title>
  <meta name="description" content="{esc(desc)}">
  <link rel="canonical" href="{url}">
  <meta name="color-scheme" content="dark">
  <meta name="theme-color" content="#0c1522">
  <link rel="icon" href="assets/img/favicon-32.png" type="image/png" sizes="32x32">
  <link rel="icon" href="assets/img/favicon.svg" type="image/svg+xml">
  <link rel="apple-touch-icon" href="assets/img/apple-touch-icon.png">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="DGF-Bench">
  <meta property="og:title" content="{title}">
  <meta property="og:description" content="{esc(desc)}">
  <meta property="og:url" content="{url}">
  <meta property="og:image" content="https://dgfbench.com/assets/img/og.png">
  <meta property="og:image:width" content="1200">
  <meta property="og:image:height" content="630">
  <meta property="og:image:alt" content="DGF-Bench: a benchmark for simulating and auditing deception against multi-agent governance boards">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="{title}">
  <meta name="twitter:description" content="{esc(desc)}">
  <meta name="twitter:image" content="https://dgfbench.com/assets/img/og.png">
{theme}
  <link rel="stylesheet" href="assets/css/site.css">
  <link rel="stylesheet" href="assets/css/sitemap.css">
  <script src="assets/js/site.js" defer></script>
</head>
<body>
  <a class="skip-link" href="#main">Skip to content</a>

{header}

  <main id="main" tabindex="-1">

    <section class="page-hero" aria-labelledby="page-title">
      <div class="container">
        <p class="eyebrow">Site map</p>
        <h1 id="page-title">Site map</h1>
        <p class="lede">{esc(desc)}</p>
      </div>
    </section>

    <section class="section" aria-labelledby="pages">
      <div class="container">
        <div class="section__head">
          <h2 id="pages">Pages</h2>
          <p class="lede">Each page with what it covers and a link to each of its sections.</p>
        </div>
        <div class="grid grid--2 smap-pages">
{pages}
        </div>
      </div>
    </section>

    <section class="section section--alt" aria-labelledby="attack-pages">
      <div class="container">
        <div class="section__head">
          <h2 id="attack-pages">Attack pages</h2>
          <p class="lede">One page per attack, by family: how it works, what the agent sees, its September 2026 results on six models and the command that runs it.</p>
        </div>
        <div class="smap-families">
{families}
        </div>
      </div>
    </section>

    <section class="section" aria-labelledby="elsewhere">
      <div class="container">
        <div class="section__head">
          <h2 id="elsewhere">Elsewhere</h2>
          <p class="lede">The paper, the code and the package of DGF-Bench, outside this site.</p>
        </div>
        <ul class="smap-links">
{elsewhere}
        </ul>
        <p class="small muted mt-6">For search engines, the same pages are listed in <a href="sitemap.xml">sitemap.xml</a>.</p>
      </div>
    </section>

  </main>

{footer}
"""


# Sitemap ------------------------------------------------------------------------------------------------

TODAY = datetime.date.today().isoformat()


def lastmod(rel):
    """Date of the last commit of a file, or today if it has uncommitted changes (or git is unavailable)."""
    try:
        dirty = subprocess.run(["git", "status", "--porcelain", "--", rel], cwd=ROOT, capture_output=True,
                               text=True, check=True).stdout.strip()
        if not dirty:
            date = subprocess.run(["git", "log", "-1", "--format=%cs", "--", rel], cwd=ROOT, capture_output=True,
                                  text=True, check=True).stdout.strip()
            if date:
                return date
    except (OSError, subprocess.CalledProcessError):
        pass
    return TODAY


def sitemap(attack_pages):
    roots = {p.name for p in ROOT.glob("*.html")} - NOT_IN_SITEMAP
    listed = {f for f, _, _ in SITE_PAGES}
    if roots != listed:
        fail("SITE_PAGES does not match the pages at the site root: "
             f"missing {sorted(roots - listed)}, unknown {sorted(listed - roots)}")
    rows = []
    for f, _, prio in SITE_PAGES:
        loc = SITE if f == "index.html" else SITE + f
        rows.append((loc, lastmod(f), prio))
    for f in attack_pages:
        rows.append((f"{SITE}{OUT_DIR}/{f}", lastmod(f"{OUT_DIR}/{f}"), ATTACK_PRIORITY))
    body = "\n".join(f"  <url><loc>{loc}</loc><lastmod>{mod}</lastmod><priority>{prio}</priority></url>"
                     for loc, mod, prio in rows)
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + body + "\n</urlset>\n")


def write(path, text):
    """Write with LF line ends, only when the content changes."""
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    path.write_text(text, encoding="utf-8", newline="\n")
    return True


def main():
    src = (ROOT / "attacks.html").read_text(encoding="utf-8")
    data = json.loads((ROOT / "data" / "results.json").read_text(encoding="utf-8"))
    template = (ROOT / "tools" / "page_template.html").read_text(encoding="utf-8")
    chrome = read_chrome(template, sub_page=True)
    cards, fams = read_cards(src), read_families(src)
    models, by_id = data["models"], {a["id"]: a for a in data["attacks"]}
    if len(cards) != len(by_id):
        fail(f"{len(cards)} cards in attacks.html, {len(by_id)} attacks in data/results.json")
    if set(fams) != {f["key"] for f in data["families"]}:
        fail("the family sections of attacks.html do not match the families of data/results.json")
    for c in cards:
        a = by_id[c["n"]]
        if a["slug"] != c["slug"] or a["family"] != c["fam"]:
            fail(f"attack {c['n']}: the card ({c['slug']}, {c['fam']}) and the data ({a['slug']}, {a['family']}) differ")
        if c["results"] != results_html(a, models):
            fail(f"attack {c['n']} ({c['slug']}): the static results of the card differ from data/results.json")

    out = ROOT / OUT_DIR
    out.mkdir(exist_ok=True)
    changed, pages = 0, []
    for c in cards:
        text = build_page(c, cards, by_id[c["n"]], models, fams, data["families"], chrome, data["package"]["version"])
        changed += write(out / c["page"], text)
        pages.append(c["page"])
    for old in sorted(out.glob("*.html")):  # pages of attacks that no longer exist
        if old.name not in pages and GENERATED in old.read_text(encoding="utf-8")[:400]:
            old.unlink()
            print(f"removed {OUT_DIR}/{old.name}")
    smap = write(ROOT / SITEMAP_PAGE, build_sitemap_page(cards, fams, data["families"], read_chrome(template, sub_page=False)))
    sm = write(ROOT / "sitemap.xml", sitemap(pages))
    print(f"{len(pages)} attack pages in {OUT_DIR}/ ({changed} written); {SITEMAP_PAGE} "
          f"({'written' if smap else 'unchanged'}); sitemap.xml with {len(SITE_PAGES) + len(pages)} pages "
          f"({'written' if sm else 'unchanged'})")


if __name__ == "__main__":
    main()
